project:
  type: website
  output-dir: docs

website:
  title: "ENGL 272 Narratives"
  sidebar:
    style: "docked"
    background: light
    foreground: primary
    border: true
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: "---"
      - section: "Blog Posts"
        contents:
          - post1.qmd
          - post2.qmd
          - post3.qmd
          - worksCited.qmd

         

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-location: left
    toc-expand: 1



