---
title: "Queer Coded Villainy"
---

## Marquis de Sade {.unnumbered .unlisted}

The queer coded villain is a product of the Hays Code in 1930s Hollywood. The code limits what is allowed to be shown on screen, particularly with regards to moral purity. Specifically, homosexuality and other kinds of “sexual perversion” is not allowed to be shown in a positive light. As such, only villains are allowed to exhibit characteristics that might be read as queer (Kim 158, 159).	 This phenomenon persists in the language of film passed the enforcement of the Hays Code, leading to the trope of the queer coded villain. In Marquis de Sade’s Justine, decades before this trope was codified, a similar phenomenon appears in the character of M. de Bressac, yet reveals a bigger picture about de Sade’s view on social norms and transgression. 

Bressac is a noble man and one of Justine's tormentors throughout the story, introduced with an explicit act of homosexuality. Bressac’s queerness is directly tied to his misogyny, treated as an extension of his villainy. His hatred of women leads to the mistreatment of Justine and the need to kill his mother. He expresses frequent contempt for women, portraying them as worthless only insofar as to what they can offer him. His speech on motherhood emphasizes the idea that every maternal act is inherently selfish and from which men are supposed to divorce themselves. 

Yet, despite his queerness being portrayed as inherently villainous, as with his other atrocity, Bressac exhibits a different perspective on his behaviors.

> I suppose that in a society where it is agreed that incest … should be a crime those who practise it will be unhappy because the weight of the opition, law and religion will combine to cool theire pleasure. Those who would like to commit this crime and those who dare not because of these restrictions will also be unhappy. Imagine that in a neighboring society incest not a crime: those who do want to practise it will be happy. The same thing can be said of all the other acts which are wrongfully considered as crimes.
>
> -- *Sade 66*

In this passage, we see that Bressac views the framing of his transgression as unlawful to be meaningless. He argues that certain behaviors are only made illegal because of a worship of goodness, and that social convention is the only thing that attributes goodness or villainy to each act. Extending on that, one could view this as a transgressive view of queerness, that its villainy is socially constructed and not due to any inherent characteristics. 

In portraying the character of Bressac, Marquis de Sade depicts his queerness among his other social and moral transgressions, essentially coding it as part of Bressac’s villainy. But the character himself exists as an antithesis to the social construct of morality and is himself a defense for these transgressions. And in proving the constructed nature of morality, Bressac is able to present queerness in a much more progressive way than first depicted. 