---
title: "Of Forms, Fictionality,and the Framing of One Life"
---

## Benjamin Franklin, Frederick Douglass, and Johann Wolfgang von Goethe {.unnumbered .unlisted}

As a fiction writer, I am fascinated by forms and mediums in storytelling. In particular, I would like to investigate forms of narrative that straddle the line between fiction and nonfiction. In one direction, we have works of fiction that attempt to present itself as reality, such as epistolary novels, found footage movies or other kinds of stories that involve a large degree of meta fiction. In the other direction, we have works that are purportedly nonfiction, such as memoirs, biographies, or biopics, but carry a certain license for inaccuracies and rewriting of facts. This latter category might seem more nebulous and even contentious, as one would argue that memoirs and biographies are categorically nonfiction. However, in packaging real historical facts into narratives that are enjoyable and satisfying for readers, as opposed to being a mere textbook, works in these genres are often allowed a degree of creative freedom. In fact, the mere act of collecting facts and framing them into, say, a memoir is itself transformative and not entirely factual.  
	
With regards to Benjamin Franklin’s Autobiography, one can witness the genesis of the autobiography as a genre. Despite its express purpose to record the facts of one’s life, the autobiography is a curated view of one’s life, framed in the way its author wishes to perform to the public. As such, every act of omission, and by extension inclusion, is deliberate. Further than that, given the extent to which writing could surpass one’s death, the autobiography is a fossilized version of something as ephemeral and all-encompassing as one’s life, typically with a specific audience in mind. 

Much of the composition of The Autobiography was collected from disparate pieces of writings by Franklin and he himself never used the title “autobiography” (Shurr 435). As such, it is hard to ascertain his intentions behind the work. Depkat describes Franklin’s Autobiography as “an act of identity politics in a situation of uncertainty that aims at constructing the normative ideal of a model citizen for the new republic and its revolutionary experiment in democracy” (60). Part Two of the Autobiography is explicitly framed by two letters written by Abel James and Benjamin Vaughan, functioning similarly to a preface that provides a piece of writing with credentials:

> The Influence Writings under that Class have on the Minds of Youth is very great, and has no where appeared so plain as in our public Friends’ Journals. It almost insensibly leads the Youth into the Resolution of endeavoring to become as good and as eminent as the Journalist. 
>
> -- *Franklin 1373*

> It is in youth that we plant our chief habits and prejudices. … But your Biography will not merely teach self-education, but the education of a wise man … and invite all wise men to become like yourself; and other men to become wise. … but at the same time we may see that though the event is flattering, the means are as simple as wisdom could make them; that is depending upon nature, virtue, thought, and habit.
>
> -- *Franklin 1375*

James’s letter portrays Franklin’s writing as a tool to be directed at the Youth of America, while Vaughan highlights the virtues of wisdom and habit. From this framing, the Autobiography emerges as a didactic tool more than a record of one’s life, utilizing the supposed factuality of the text as a mean to promote certain moral qualities. The interweaving of letters and personal journal entries reinforce the form of the autobiography as deeply personal yet true to life. However, this didactic goal has the potential to skew the exclusion and inclusion of certain facts to achieve this goal. 

A large portion of the Autobiography is reserved for Franklin’s active role in reshaping his own life through good habits and moral virtues. His effort begins with the Junto, a club where he and his acquaintances gather to discuss politics and philosophy and compose them into essays: 

> I should have mention’d before, that in the Autumn of the preceding Year, I had form’d most of my ingenious Acquaintance into a Club, for mutual Improvement, which we call’d the Junto. … The Rules I drew up, requir’d that every Member in his Turn should produce one or more Queries on any Point of Morals, Politics or Natural Philosophy, to be discuss’d by the Company, and once in three Months produce and read an Essay of his own Writing or any Subject he please. 
>
> -- *Franklin 1361*

The Junto Club exemplifies the spirit of sharing means for self-improvement that is the Autobiography’s aim. A collective of individuals with a shared goal of cultivating more knowledge and helping each other improve, with set schedules and customs. This affinity for structure is continued with his Thirteen Virtues.

> It was about this time that I conceiv’d the bold and arduous Project of arriving at moral Perfection. 
>
> -- *Franklin 1383*

He went to list out the Thirteen Virtues along with a detailed schema of personal schedule where every hour of the day is allocated a place. There is something almost too modern about the tone of the book. It is in line with the modern genre of self-help books, which purportedly attempt to shed light on the special components of life that one could identify and improve on. These self-help books always seek to reframe the mundanity of everyday life into buzzwords and principles, so as to create a schema for achieving a certain ideal of life that their authors want to convey to the audience. 

> I enter'd upon the Execution of this plan for Self Examination, and continu'd it with occasional Intermissions for some time. I was surpris'd to find myself so much fuller of Faults than I had imagined, but I had the Satisfaction of seeing them diminish. … But on the whole, tho' I never arrived at the Perfection I had been so ambitious of obtaining, but fell far short of it, yet I was by the Endeavour made a better and a happier man than I otherwise should have been, if I had not attempted it; As those who aim at perfect Writing by imitating the engraved Copies, tho' they never reach the wish'd for Excellence of those Copies, their Hand is mended by the Endeavor, and is tolerable while it continues fair & legible.— 
>
> -- *Franklin 1389, 1391*

However, despite the emphasis on these moral virtues, Franklin removes the guilt associated with the lack of these virtues and underscores the value of growth and aspiring to these ideals in and of themselves. It does not seek to promote his Virtues as the only way to achieve growth, but the act of trying to achieve it as the focus. In a sense, Franklin’s desire to shape his life and bring it to a platonic ideal of morality is in parallel with the form of the autobiography, attempting to reconfigure his journal entries into a cohesive guide. Conversely, the autobiography, as a form, is an extension of this desire to redesign one’s life. Franklin is crafting the model of a self-made man through the act of recollecting his life into an autobiography as much as the attempt at transforming his life through moral virtues. 
	
It is fascinating, then, to contrast this model of the self-made man in Franklin’s Autobiography to Douglass’ Narrative, both in the ways that Douglass was able to utilize this form, but also is limited by his own lived experiences as a formerly enslaved person. Olney describes the paradoxical nature of slave narratives, in that they are created to and typically adhere to portraying “the realities of the institution of slavery, almost never the intellectual, emotional, moral growth of the narrator”, while the form of the autobiography is meant to use “present memory [to reflect] over past experience on its way to becoming present being” such “that events are lifted out of time to be resituated not in mere chronological sequence but in patterned significance” (47, 51). In the same article, Olney acknowledges that Douglass’ Narrative is an outlier among slave narratives due to his reflection from his current position as a freed man and his past as an enslaved person (55). In other words, Douglass’ utilization of the autobiography form is not through the collection of facts but through his reflections on them. 
	
In the very first chapter, Douglass lays out the fact of his past but also includes a present perspective of what this past meant to him, and to the institution of slavery as a whole:

> I was born in Tuckahoe, near Hillsborough, and about twelve miles from Easton, in Talbot county, Maryland. I have no accurate knowledge of my age, never having seen any authentic record containing it. By far the larger part of the slaves know as little of their ages as horses know of theirs, and it is the wish of most masters within my knowledge to keep their slaves thus ignorant. I do not remember to have ever met a slave who could tell of his birthday. They seldom come nearer to it than planting-time, harvest-time, cherry-time, spring-time, or fall-time. 
>
> -- *Douglass, ch. 1*

The lack of knowledge about his own age is emphasized, along with an intentional avoidance of giving his name. The withholding of Douglass’ name, in particular, ties into the larger arc of the Narrative, in which the readers only learn of his name once he was a free man. In addition, Douglass contemplates on the role that withholding an enslaved person’s age and birthday plays in the institution of slavery, as well as placing a clear separation between ‘I’ (Douglass himself) and ‘they’ (enslaved people). There is a clear separation of perspective, a mediating of past and present. We can observe the intentional use of writing and rhetorics as part of reclaiming his sense of control over his own life, and the fact he is now able to deconstruct and process his past. This theme of writing as a tool for control of one’s life is echoed throughout the Narrative. 

> During this time, I succeeded in learning to read and write. In accomplishing this, I was compelled to resort to various stratagems. I had no regular teacher. My mistress, who had kindly commenced to instruct me, had, in compliance with the advice and direction of her husband, not only ceased to instruct, but had set her face against my being instructed by any one else. … All this, however, was too late. The first step had been taken. Mistress, in teaching me the alphabet, had given me the inch, and no precaution could prevent me from taking the ell. 
>
> -- *Douglass, ch. 7*

The act of reading and writing, here, is directly tied to transgression and as the first step to breaking away from the chains of slavery. Through his literacy, Douglass learned about abolitionism and gained a stronger sense of his own struggle and discontent. In a way, his eventual career as a writer and the writing of his Narrative is a continuation of his autonomy. 

But, if Franklin’s Autobiography was written to create a model for other youths to emulate, is there a similar didactic purpose to Douglass’ Narrative?

> But before narrating any of the peculiar circumstances, I deem it proper to make known my intention not to state all the facts connected with the transaction. My reasons for pursuing this course may be understood from the following: First, were I to give a minute statement of all the facts, it is not only possible, but quite probable, that others would thereby be involved in the most embarrassing difficulties. Secondly, such a statement would most undoubtedly induce greater vigilance on the part of slaveholders than has existed heretofore among them; which would, of course, be the means of guarding a door whereby some dear brother bondman might escape his galling chains. 
>
> -- *Douglass, ch 11*

Throughout the Narrative, Douglass indeed talks about the bonds of fellow enslaved people and, similar to Franklin, expresses a desire here to instruct others on his means of escape, of transforming his own life. And yet, due to the nature of the text, he cannot. As such, his ability to reshape and affect his own life, and in a way his own lived experience, is kept limited. Indeed, when we consider that the target audience of his Narrative, and slaves narratives in general, is white abolitionist or potential supporters, this work, as an autobiography, is meant to be informational but not didactic. Thus, through leveraging the form of the autobiography and the model of the self-made man, Douglass’ Narrative is declaring his own personhood, and yet is still limited by his own past experiences and the genre of slave narratives. 

On the other side of works that straddle the line between fiction and non-fiction, let’s consider epistolary novels such as The Sorrows of Young Werther. One of the major conceits of the epistolary form is to portray the fiction as closer to reality, that the fiction one is reading is a collection of real forms of writings, such as letters, diary entries or newspaper clippings. This form is attempting to decrease the level of suspension of disbelief. In Werther, the story is portrayed, particularly in the first book, as a series of letters written by the titular character to a close friend named Wilhelm.

> How glad I am to be away! My dear friend, what a thing the human heart is! I leave you, whom I love so much, from whom I was inseparable, and I am glad! You will forgive me, I know. 
>
> -- *Goethe, 4 May 1771*

>You’ve long known my habit of settling in somewhere, setting up home in some cosy place and lodging there in all simplicity and frugality. Here too I have discovered an attractive spot. 
>
> -- *Goethe, 26 May 1771*

>Such a night that was! Wilhelm, now I can bear anything. I shan’t see her again. Oh why can I not fly into your arms and tell you, my dear friend, with tears and raptures what feelings assault my heart! But I sit here and can’t get my breath and try to calm myself and await the morning and the horses are ordered for sunrise. 
>
> -- *Goethe, 10 September 1771*

> I had something in mind which I didn’t want to tell you about until I was done, but now that nothing has come of it, I might as well. I wanted to enlist and go to war. 
>
> -- *Goethe, 25 May 1772*

This choice in form endears Werther to the audience, in a more intimate way than even a first person perspective could. A first person perspective, despite its seeming small narrative distance, could still obscure the narrator’s intimate thoughts due to a necessary suspension of disbelief. Readers are not, typically, able to read other’s minds, and would interpret the text of the story as artificial and unreliable. The furthering of narrative distance through a second person, in this case Wilhelm, actually eases the suspension of disbelief. And, since Wilhelm is described as a close and long time friend to whom Werther could disclose his most personal and vulnerable thoughts, the readers can trust Werther and fully immerse in his narration of the story. We are primed to like Werther and engage deeper with his thoughts and feelings. 

Despite the self-insert nature of Wilhelm, as the story progresses, a certain characterization of Wilhelm emerges, through small references to details that the readers are not privy to on Werther’s side of the correspondence.

> Why haven’t I written to you? — You ask me that and yet you are a scholar. You ought to be able to guess that I am well, and indeed — 
>
> -- *Goethe, 16 June 1771*

> Since you are so concerned that I shouldn’t neglect my drawing I’d rather pass over the whole subject in silence than tell you that for some time now I have done very little. (Goethe, 24 July 1771)
Believe me, my dear Wilhelm, I certainly didn’t have you in mind when I said I couldn’t bear people who insist we should accept the inevitable. It really did not occur to me that you might incline to that opinion. And when all’s said and done, you are right. Only one thing, my dear friend: Either-Or is rarely an adequate formula for life. … You won’t take it amiss then if I concede your entire argument and try nevertheless to wriggle between the Either and the Or. 
>
> -- *Goethe, 8 August 1771*

>I must go. I thank you, Wilhelm, for deciding me as I wavered. For two weeks I have been living with the thought of leaving her. I must go away. She is in town again, at a friend’s. And Albert — and — I must go away from here. 
>
> -- *Goethe, 3 September 1771*

> Thank you for your two letters. I didn’t reply because I was keeping this letter back until my discharge from the Court came through. … I don’t like to tell you how reluctant they let me go, nor what the Minister wrote: you would all break out in fresh lamentations. 
> 
> -- *Goethe, Postscript 19 April 1772*

Wilhelm is portrayed as a scholar, one who can and does engage with Werther’s digressions and contemplations. He cares about Werther, answering his correspondence, inquiring about his well being and giving him advice. This further primes the readers to engage with Werther discussions and to care about his life, as we have already positioned ourselves as Wilhelm. In addition, this inclusion of a second character gives Werther space to grow in complexity as opposed to a more singular form such as diary entries. And yet, there was a distinct choice to withhold any physical manifestation of Wilhelm, such as his own correspondence to Werther. This allows for all the benefits of the letter form while further emphasizing the theme of sorrow and loneliness. As we are only privy to one half of the correspondence, as the story progresses and Werther’s psyche spirals out of control, there is a building sense of unease, that Werther is writing into a void with no response. The reader might start to question whether Wilhelm exists at all, adding to the build up of sorrow and despair that colors the second half of the novel. The novel, then, reads like a personal diary, with the added sadness of an imaginary listener. 

The second layer of the epistolary form is the framing device of an unnamed narrator who is collecting Werther’s letters and putting together the story of his life. 

>Everything I could discover about poor Werther’s story I have diligently gathered together and lay it before you now and know that you will thank me. His mind and his character will compel your admiration and your love, and his fate will compel your tears. 
> 
> -- *Goethe, book 1 preface*

This narrator features more prominently in book 2 as the regular flow of letters is interrupted with their own narrations in an attempt to fill in the blanks of the last days of Werther’s life.

> I have made it my business to gather exact information from the mouths of those who could have a good knowledge of his story — which is straightforward, and except in a few trivial details all versions of it tally. Opinions differ and judgements are divided only when it comes to the ways of thinking and feeling of the people involved. 
> 
> -- *Goethe, book 2*

This framing device creates a second layer of realism to the story, presenting the exact circumstances for a collection of letters to exist, while at the same time bringing the novel closer to a typical first person perspective. In addition, the added story of the narrator presents complexity to the story. We get the sense that what we can learn from Werther’s correspondence is incomplete, and that we could potentially be missing important aspects of his life. This framing device forces the readers to think about the form itself instead of relegating the epistolary aspect to a mere stylistic choice. The combination of the first layer of epistolary, Wilhelm, and the framing device offers a unique atmosphere of loneliness, one that insists upon the reader through two people that care deeply about Werther. We witness Werther trying to wade through the passions and sorrows of young adulthood with so much anguish and emotions that go unheard until post mortem. 

In a sense, this form is quite analogous to the autobiography discussed earlier. The conceit of the entire book is a recollection of one person’s life but only through the lens of his correspondence. All three works discussed above attempt to wrangle one life under the framing of some narrative form and, in the process, cross the line between fiction and nonfiction, whether through the mirage of realism on fiction or the purposeful rerendering of reality. It is hard to write about one’s life, and harder still to glean one’s life merely from writing, and often enough, one would have to reject any notion of what is fiction and what is reality.