---
title: "An Inexact Copy is Good, Actually: Capturing Likeness Via Art"
---

## The House of Seven Gables, Bartleby, and Emily Dickinson {.unnumbered .unlisted}

Living in the age of technology, I often forget how miraculous the art of photography is. There is something almost magical in being capable of capturing a moment in time, to make frozen what is ephemeral. Certainly, with smartphones and cameras, anyone is able to do this conveniently and inexpensively. Yet, if we look at the long history of humankind, it is through art and writing that we attempt to do the same thing. I would like to investigate the use of art as a means of copying or capturing a person, and the way this is used as a narrative element in The House of Seven Gables, Bartleby, and the poems by Emily Dickinson.

The House of Seven Gables features several different forms of art, all of which have the capacity to capture a person’s essence, preserving it beyond their death, but transforming the original through an inexact copy. The first form, and one that is closest to a perfect capturing of one’s likeness is daguerreotype, used by the character of Holgrave. Daguerreotype is one of the first practical processes of photography, invented in 1839. It utilizes a silver plate sensitive to light, creating a unique and extremely delicate image that cannot be made into copies (International Center of Photography 130, 131). As such, daguerreotype is as close as possible during this time period to capture a true likeness of a person, and this almost magical process is associated with Holgrave, a descendant of the alleged wizard Maule. Cohen makes a compelling argument that Holgrave’s daguerreotype of the Judge at the end is an act of magic due to the physical impossibility of the dark parlor (49). This supernatural aspect notwithstanding, daguerreotype is described as “pictures [made] out of sunshine” by Holgrave, and is generally portrayed as the work of sunlight itself, as opposed to an artist painting a portrait (Hawthorne, ch. 6). 

> [Holgrave said:] “There is a wonderful insight in Heaven’s broad and simple sunshine. While we give it credit only for depicting the merest surface, it actually brings out the secret character with a truth that no painter would ever venture upon, even could he detect it. … Now, the remarkable point is, that the original wears, to the world’s eye … an exceedingly pleasant countenance, indicative of benevolence, openness of heart, sunny good-humor, and other praiseworthy qualities of that cast. The sun, as you see, tells quite another story, and will not be coaxed out of it, after half a dozen patient attempts on my part. Here we have the man, sly, subtle, hard, imperious, and, withal, cold as ice.” 
> 
> -- *Hawthorne, ch. 6*

In this passage, Holgrave describes his daguerreotype of Judge Pyncheon, stating that despite his outward appearance being generally agreeable to most people, the daguerreotype shows a cruel and deceitful man, one that Phoebe initially mistakens for Colonel Pyncheon. The novel deals a lot with the dissonance between a person’s outward appearance and their inner self, particularly in the characters of the Judge and Clifford. Here, daguerreotype, as an art form, is ascribed the ability to reveal the true inner self of its subject. Similarly, at the end of the novel, it is Holgrave’s daguerreotype of the Judge’s dead body that becomes the proof of Clifford and Hepzibah’s innocence. Thus, despite proposing to capture the true likeness of a person, daguerreotype is not an exact copy, and provides additional dimension to its subject
	
Another form of art used to depict a person in Seven Gables is painting. Hepzibah has a miniature painting of Clifford which she cherishes and the portrait of Colonel Pyncheon plays a pivotal role in the story. There is a certain contrast between daguerreotype and paintings, in that the latter, from being created by a person as opposed to sunlight itself, is imperfect and does not always capture everything about a person. 

> Malbone’s miniature, though from the same original, was far inferior to Hepzibah’s air-drawn picture, at which affection and sorrowful remembrance wrought together. Soft, mildly, and cheerfully contemplative, with full, red lips, just on the verge of a smile, which the eyes seemed to herald by a gentle kindling-up of their orbs! Feminine traits, moulded inseparably with those of the other sex! 
> 
> -- *Hawthorne, ch. 4*

The miniature is shown as inferior to the mind image that Hepzibah has of Clifford, being unable to capture his gentleness. Painting creates an inexact copy. Despite this inexactness, these paintings still preserve some versions of the original past their lifetime. The portrait of Colonel Pyncheon, throughout the novel, seems to maintain his tyrannical grip on the house and, during the night of the Judge’s death, becomes a portal for past Pyncheon to come back as spectres.  

> In one sense, this picture had almost faded into the canvas, and hidden itself behind the duskiness of age; in another, she could not but fancy that it had been growing more prominent and strikingly expressive, ever since her earliest familiarity with it as a child. For, while the physical outline and substance were darkening away from the beholder’s eye, the bold, hard, and, at the same time, indirect character of the man seemed to be brought out in a kind of spiritual relief. … [Old paintings] acquire a look which an artist (if he have anything like the complacency of artists nowadays) would never dream of presenting to a patron as his own characteristic expression, but which, nevertheless, we at once recognize as reflecting the unlovely truth of a human soul. In such cases, the painter’s deep conception of his subject’s inward traits has wrought itself into the essence of the picture, and is seen after the superficial coloring has been rubbed off by time. 
>
> -- *Hawthorne, ch. 4*

In this passage, however, we see the painting as a conduit for the transformative property of both the artist and time. Through being depicted, Colonel Pyncheon’s likeness is imbued with the artist’s intention and captured into painting. This painting then becomes subject to time which has a similar revelatory property to that of sunlight in daguerreotype, underscoring the Colonel’s cruelty. Thus, we are shown that both paintings and daguerreotype create inexact copies of the original subject, speaking to the transformative capacity of art in capturing a person’s likeness. Art is able to obscure or reveal richer aspects of the original subject. 
	
A more subtle form of inexact copying is through reproduction and generational succession. The novel portrays several cases of modern characters mirroring, narratively and sometimes physically, people from the past. The entire premise of the novel revolves around curses and properties that are maintained and passed down across generations. The Pyncheon family, and the Colonel in particular, seems to have a self-sufficient method of keeping themselves copied, either through the physical Pyncheon House itself, or through the Colonel’s portrait as discussed above. Thus, the recurrence of physical traits through genetics can be seen as an extension of this maintenance. 

> In almost every generation, nevertheless, there happened to be some one descendant of the family gifted with a portion of the hard, keen sense, and practical energy, that had so remarkably distinguished the original founder. His character, indeed, might be traced all the way down, as distinctly as if the Colonel himself, a little diluted, had been gifted with a sort of intermittent immortality on earth. At two or three epochs, when the fortunes of the family were low, this representative of hereditary qualities had made his appearance, and caused the traditionary gossips of the town to whisper among themselves, “Here is the old Pyncheon come again! Now the Seven Gables will be new-shingled!” 
> 
> -- *Hawthorne, ch. 1*

The Judge is constantly remarked as resembling the Colonel, Phoebe is associated with the beauty and purity of Alice, and Holgrave plays the role of the wizard Matthew Maule. Once again, we see an affinity for transformation as opposed to exact copies of the original. The Judge, who greatly resembles the Colonel, represents the cruelty that originates the tragedy of the novel and its continuation is treated like a curse. In a way, it is an extension of the unjust legality that allows the Pyncheon family to continue benefiting from a piece of stolen land. Meanwhile, Holgrave deliberately chooses to not follow his predecessor’s example and holds hypnotic control over Phoebe. Their union in the end creates a break in the generational rivalry of the two families. Thus, once more, inexact copies are a means of transforming and amending the original.

The poems of Emily Dickinson play with the idea of using art to transform oneself in a slightly different way. Instead of having these acts of copy as a literary element, the poems themselves are Dickinson's way of transforming and deconstructing her own physical body. Severa of Dickinson’s poems, such as “I felt a cleaving in my mind”, describe a discomfort and disassociation between her inward identity and physical body.

> I felt a Cleaving in my Mind —
>
> As if my Brain had split —
>
> I tried to match it — Seam by Seam —
>
> But could not make them fit. 
>
> -- *Dickinson*

She describes a split in her brain that cannot be reconciled, evoking the Victorian dual-brain theory that suggests a possible existence of two different personalities across the two brain hemisphere (Stiles 31). Needlework is referenced as unable to bridge this disconnect. Yet, through putting this discomfort into poetry, Dickinson was able to visualize it through the use of em-dashes and line breaks, transforming the physical into a medium that could be manipulated. Similarly, in “One Need Not be a Chamber — to be Haunted”, Dickinson materializes her inner thoughts and turmoil by representing herself as a chamber, thus deconstructing nebulous emotions as physical objects that can be easily understood.

Bartleby, on the other hand, presents the act of exact copying, displaying it as an antithesis to creation. The novel deals with scriveners, or law copyists. As such, their form of writing is producing an exact copy of the original. This contrasts with the way that inexact copying is able to add more dimensions to its subject. The scrivener’s exact copy provides nothing new to its original. This lack of artistic direction is corroborated by the mechanical nature of the scrivener characters in the story. 

> It was fortunate for me that, owing to its peculiar cause—indigestion— the irritability and consequent nervousness of Nippers, were mainly observable in the morning, while in the afternoon he was comparatively mild. So that Turkey’s paroxysms only coming on about twelve o’clock, I never had to do with their eccentricities at one time. Their fits relieved each other like guards. When Nippers’ was on, Turkey’s was off; and vice versa. This was a good natural arrangement under the circumstances. 
> 
> -- *Melville*

Nippers and Turkey are portrayed quite mechanically, both having certain quirks and traits that change throughout the day, but consistent across each day. And they complement each other’s mood swing by having a perfect offset. As Melville puts it in this paragraph, “when Nippers’ was on, Turkey’s was off; and vice versa”, like a power switch. 

Of course, the titular character himself is described to be “[writing] on silently, palely, mechanically” (Melville). Bartleby works efficiently and single mindedly on his copies while living at his office. He is defined only by his work. His refusal to examine his finished copies points to the idea that there are no further values to the act of copying, as every finished product adds nothing to the original. Thus, copying is the antithesis to art, and the people doing this line are rendered into machines due to its lack of creation. This form of writing physically drains the creativity away from its practitioners. Bartleby eventually suffers from an impaired vision due to the strain of his work and begins refusing to engage with the act of copying at all. Thus, the lack of creation kills even the mere act of making copies. 

Daguerreotype, painting and poetry are all forms of art attempting to capture something nebulous into a more physical form, at times attempting to copy as exact as possible the original. And yet, the true power of these forms lies in their transformative capabilities, imbuing more dimensions into the subject, as is the nature of creativity. It becomes an avenue for the artist to perform an act of creation. Thus, replacing this with exactness will result only in destruction.