---
title: "Works Cited"
---

Cohen, Lara Langer. “What's Wrong with This Picture?: Daguerreotypy and Magic in The House of the Seven Gables.” Arizona Quarterly: A Journal of American Literature, Culture, and Theory, vol. 60, no. 1, 2004, pp. 39-69. Project MUSE, https://dx.doi.org/10.1353/arq.2004.0010.

Depkat, Volker. “Autobiography as Political Legacy in Transition Periods. Benjamin Franklin and Konrad Adenauer Compared.” European Journal of Life Writing, vol. 9, 2020, pp. BE51–74. https://doi.org/10.21827/ejlw.9.37325.

Dickinson, Emily. Selected Poems of Emily Dickinson. Edited by James Reeves, Macmillan Company, 1959.

Douglass, Frederick. Narrative of the life of Frederick Douglass. Dover Publications, 1995.

Franklin, Benjamin. “The Autobiography.” Benjamin Franklin: Writings, Library of America, 1987, pp. 1358-1394.

Goethe, Johann Wolfgang von. The Sorrows of Young Werther. Translated by David Constantine, OUP Oxford, 2012.

Hawthorne, Nathaniel. The House of the Seven Gables: An Authoritative Text, Contexts, Criticism. Edited by Robert Steven Levine, W. W. Norton, 2020.

International Center of Photography. Encyclopedia of Photography. 1st ed., Crown, 1984.

Kim, Koeun. “Queer-coded villains (and why you should care).” Dialogues@ Ru, 2017, pp. 156-165.

Melville, Herman. “Bartleby.” Edited by Peter M. Coviello. Billy Budd, Bartleby, and Other Stories, Penguin Publishing Group, 2016.

Olney, James. “‘I Was Born’: Slave Narratives, Their Status as Autobiography and as Literature.” Callaloo, vol. 20, 1984, pp. 46–73. JSTOR, https://doi.org/10.2307/2930678.

Sade, Marquis de. Selected Writings of De Sade. Translated by Leonard de Saint-Yves, British Book Centre, 1954.

Shurr, William H. “Now, Gods, Stand Up for Bastards’: Reinterpreting Benjamin Franklin’s Autobiography.” American Literature, vol. 64, no. 3, 1992, pp. 435–51. JSTOR, https://doi.org/10.2307/2927746.

Stiles, Anne. Robert Louis Stevenson’s Jekyll and Hyde and the Double Brain. Cambridge University Press, 2012. Accessed 28 March 2025.

	
